version: '3'

services:
  client:
    container_name: client
    image: zip_captions
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    volumes:
      - .:/usr/src/app:delegated
    ports:
      - 4200:80