version: '3'

services:
  client:
    container_name: client
    image: zip_captions
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app:delegated
    command: [sh, -c, 'npm run start:client']
    ports:
      - 4200:4200