name: Docker Image CI/CD Staging Server

on:
  workflow_dispatch:
  push:
    branches: 
      - 'develop'
    paths:
      - 'packages/signal/**/*'
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: educoder/zip-captions-signal

      - name: Build and push client Docker image
        uses: docker/build-push-action@v4
        with:
          target: staging_signal
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
